fontsEditPage:
    path:     /edit/{id}
    defaults:
        _controller: Themes\Rozier\Controllers\FontsController::editAction
    requirements: { id : "[0-9]+" }
fontsDownloadPage:
    path:     /download/{id}
    defaults:
        _controller: Themes\Rozier\Controllers\FontsController::downloadAction
    requirements: { id : "[0-9]+" }
fontsAddPage:
    path:     /add
    defaults:
        _controller: Themes\Rozier\Controllers\FontsController::addAction
    requirements: { id : "[0-9]+" }
fontsDeletePage:
    path:     /delete/{id}
    defaults:
        _controller: Themes\Rozier\Controllers\FontsController::deleteAction
    requirements: { id : "[0-9]+" }
