---
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $backofficeMenuEntries: '%roadiz_rozier.backoffice_menu_configuration%'
            $documentPlatforms: '%roadiz_core.medias.supported_platforms%'
            $webpSupported: '%roadiz_core.assets_processing.supports_webp%'
            $nodeFormTypeClass: '%roadiz_rozier.node_form.class%'
            $addNodeFormTypeClass: '%roadiz_rozier.add_node_form.class%'

    RZ\Roadiz\RozierBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Event/'

    Themes\Rozier\:
        resource: '%kernel.project_dir%/vendor/roadiz/rozier/src/'
        autowire: true
        autoconfigure: true
        exclude:
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Services/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Events/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Traits/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Widgets/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Explorer/'

    Themes\Rozier\Controllers\:
        resource: '%kernel.project_dir%/vendor/roadiz/rozier/src/Controllers/'
        autowire: true
        autoconfigure: true
        tags:
            - container.service_subscriber

    Themes\Rozier\Explorer\FoldersProvider:
        public: true
    Themes\Rozier\Explorer\SettingsProvider:
        public: true
    Themes\Rozier\Explorer\UsersProvider:
        public: true

    Themes\Rozier\Widgets\TreeWidgetFactory: ~
    Themes\Rozier\RozierServiceRegistry:
        public: true

    roadiz_rozier.twig_loader:
        class: Twig\Loader\FilesystemLoader
        calls:
            -   prependPath: [ '%kernel.project_dir%/vendor/roadiz/documents/src/Roadiz/Resources/views' ]
            -   prependPath: [ '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/views', 'Rozier' ]
            -   prependPath: [ '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/views' ]
        tags: [ 'twig.loader' ]

    # Customized OpenIdAuthenticator for Rozier backoffice entry points
    roadiz_rozier.authenticator.open_id:
        class: RZ\Roadiz\CoreBundle\Security\Authentication\OpenIdAuthenticator
        autoconfigure: false
        arguments:
            - '@security.http_utils'
            - '@?RZ\Roadiz\OpenId\Discovery'
            - '@RZ\Roadiz\OpenId\Authentication\Provider\ChainJwtRoleStrategy'
            - '@RZ\Roadiz\OpenId\OpenIdJwtConfigurationFactory'
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '@RZ\Roadiz\CoreBundle\Security\Authentication\Manager\LoginAttemptManager'
            - 'loginPage'
            - 'adminHomePage'
            - '%roadiz_core.open_id.oauth_client_id%'
            - '%roadiz_core.open_id.oauth_client_secret%'
            - '%roadiz_core.open_id.openid_username_claim%'
            - '_target_path'
            - '%roadiz_core.open_id.granted_roles%'
