---
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $backofficeMenuEntries: '%roadiz_rozier.backoffice_menu_configuration%'
            $documentPlatforms: '%roadiz_core.medias.supported_platforms%'
            $webpSupported: '%roadiz_core.assets_processing.supports_webp%'
            $nodeFormTypeClass: '%roadiz_rozier.node_form.class%'
            $addNodeFormTypeClass: '%roadiz_rozier.add_node_form.class%'

    RZ\Roadiz\RozierBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Event/'

    Themes\Rozier\:
        resource: '%kernel.project_dir%/vendor/roadiz/rozier/src/'
        autowire: true
        autoconfigure: true
        exclude:
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Controllers/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Services/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Events/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Traits/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Widgets/'
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Explorer/'

    Themes\Rozier\Controllers\:
        resource: '%kernel.project_dir%/vendor/roadiz/rozier/src/Controllers/'
        autowire: true
        autoconfigure: true
        tags:
            - container.service_subscriber
        exclude:
            - '%kernel.project_dir%/vendor/roadiz/rozier/src/Controllers/LoginRequestController.php'

    Themes\Rozier\Explorer\FoldersProvider:
        public: true
    Themes\Rozier\Explorer\SettingsProvider:
        public: true
    Themes\Rozier\Explorer\UsersProvider:
        public: true

    Themes\Rozier\Widgets\TreeWidgetFactory: ~
    Themes\Rozier\RozierServiceRegistry:
        public: true

    roadiz_rozier.twig_loader:
        class: Twig\Loader\FilesystemLoader
        calls:
            -   prependPath: [ '%kernel.project_dir%/vendor/roadiz/documents/src/Roadiz/Resources/views' ]
            -   addPath: [ '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/views', 'RoadizRozier' ]
        tags: [ 'twig.loader' ]


    #
    # Open ID
    #
    RZ\Roadiz\OpenId\OAuth2LinkGenerator:
        arguments:
            - '@?roadiz_rozier.open_id.discovery'
            - '@security.csrf.token_manager'
            - '%roadiz_rozier.open_id.hosted_domain%'
            - '%roadiz_rozier.open_id.oauth_client_id%'
            - '%roadiz_rozier.open_id.scopes%'

    RZ\Roadiz\OpenId\Authentication\Provider\SettingsRoleStrategy:
        arguments: [ '@RZ\Roadiz\CoreBundle\Bag\Settings' ]
        tags: [ 'roadiz_rozier.jwt_role_strategy' ]

    RZ\Roadiz\OpenId\Authentication\Provider\ChainJwtRoleStrategy: ~
    RZ\Roadiz\OpenId\Authentication\Provider\OpenIdAccountProvider: ~

    RZ\Roadiz\RozierBundle\Controller\PingController:
        arguments: ['@?profiler']
